#!/usr/bin/env bash
# ============================================================
# Xray VLESS + REALITY Installer v2
# Ubuntu 24.04+
# TCP 443 / REALITY / XTLS Vision
#
# v2 improvements:
#   - Explicit Xray built-in DNS (DoH) with IPv4 preference
#   - Freedom outbound uses Xray DNS instead of relying only on OS DNS
#   - VLESS URL includes encryption=none
#   - Better pre-flight and post-install connectivity checks
#   - Safe re-run: reuses existing Xray service and replaces only
#     the Xray config generated by this installer
#   - Dynamic Xray service group (Ubuntu commonly uses nobody:nogroup)
# ============================================================

set -Eeuo pipefail

XRAY_BIN="/usr/local/bin/xray"
XRAY_CONFIG="/usr/local/etc/xray/config.json"
XRAY_INFO="/root/xray-reality-info.txt"
XRAY_PORT="443"
FLOW="xtls-rprx-vision"
XRAY_SERVICE_USER="nobody"
XRAY_SERVICE_GROUP=""
DNS1="https+local://1.1.1.1/dns-query"
DNS2="https+local://8.8.8.8/dns-query"

SERVER_IP=""
SNI=""
UUID=""
PRIVATE_KEY=""
PUBLIC_KEY=""
SHORT_ID=""
VLESS_URL=""

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;36m'
CYAN='\033[0;36m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()   { echo -e "${GREEN}[ OK ]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*"; }
die()  { err "$*"; exit 1; }

trap 'echo; err "Installer failed at line ${LINENO}."; exit 1' ERR

if [[ "${EUID}" -ne 0 ]]; then
    die "Please run this script as root."
fi

[[ -f /etc/os-release ]] || die "/etc/os-release not found."
source /etc/os-release

if [[ "${ID:-}" != "ubuntu" ]]; then
    warn "This installer is designed for Ubuntu. Detected: ${PRETTY_NAME:-unknown}"
fi

version_ge() {
    # usage: version_ge installed required
    dpkg --compare-versions "$1" ge "$2"
}

install_dependencies() {
    info "Updating package information..."
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y

    info "Installing required packages..."
    apt-get install -y \
        curl wget jq openssl uuid-runtime ca-certificates \
        iproute2 iptables dnsutils coreutils procps

    ok "Required packages installed."
}

detect_public_ip() {
    info "Detecting public IPv4 address..."

    SERVER_IP="$(
        curl -4 -fsS --max-time 10 https://api.ipify.org 2>/dev/null || true
    )"
    if [[ -z "${SERVER_IP}" ]]; then
        SERVER_IP="$(
            curl -4 -fsS --max-time 10 https://ifconfig.me 2>/dev/null || true
        )"
    fi
    if [[ -z "${SERVER_IP}" ]]; then
        SERVER_IP="$(
            curl -4 -fsS --max-time 10 https://icanhazip.com 2>/dev/null || true
        )"
    fi

    SERVER_IP="$(echo "${SERVER_IP}" | tr -d '[:space:]')"

    [[ "${SERVER_IP}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] ||
        die "Unable to detect a valid public IPv4 address."

    ok "Public IPv4: ${SERVER_IP}"
}

check_server_internet() {
    info "Checking server DNS and IPv4 Internet connectivity..."

    local dns_output
    dns_output="$(dig +time=3 +tries=1 +short www.google.com A 2>/dev/null || true)"
    if [[ -z "${dns_output}" ]]; then
        warn "System DNS could not resolve www.google.com."
        warn "Xray v2 will use its own DoH DNS configuration."
    else
        ok "System DNS resolves www.google.com: ${dns_output%%$'\n'*}"
    fi

    if curl -4 -fsSI --max-time 10 https://www.google.com >/dev/null 2>&1; then
        ok "IPv4 Internet connectivity is working."
    else
        warn "Direct IPv4 HTTPS test failed."
        warn "The VPS provider/network may restrict outbound HTTPS."
    fi
}

check_local_port() {
    info "Checking whether TCP ${XRAY_PORT} is already in use..."

    if ss -lnt 2>/dev/null |
        awk '{print $4}' |
        grep -Eq "(:|\])${XRAY_PORT}$"; then

        # Allow a re-run when the listener is Xray itself.
        if systemctl is-active --quiet xray 2>/dev/null &&
           ss -lntp 2>/dev/null | grep -Eq "(:|\])${XRAY_PORT}\b.*xray"; then
            ok "TCP ${XRAY_PORT} is already owned by Xray; continuing."
        else
            ss -lntp 2>/dev/null | grep -E "(:|\])${XRAY_PORT}\b" || true
            die "TCP port ${XRAY_PORT} is already in use by another service."
        fi
    else
        ok "TCP ${XRAY_PORT} is available."
    fi
}

valid_domain_format() {
    local domain="$1"
    [[ -n "${domain}" ]] || return 1
    [[ "${#domain}" -le 253 ]] || return 1
    [[ "${domain}" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]] || return 1
    return 0
}

validate_sni() {
    local domain="$1"
    local dns_result=""

    valid_domain_format "${domain}" ||
        die "Invalid domain format: ${domain}"

    info "Validating SNI: ${domain}"

    dns_result="$(getent ahostsv4 "${domain}" 2>/dev/null | awk '{print $1}' | sort -u | head -n 5 || true)"
    if [[ -z "${dns_result}" ]]; then
        die "SNI does not resolve to an IPv4 address: ${domain}"
    fi

    echo "Resolved IPv4:"
    echo "${dns_result}"

    if timeout 10 bash -c "cat < /dev/null > /dev/tcp/${domain}/443" 2>/dev/null; then
        ok "TCP 443 is reachable on ${domain}."
    else
        die "Cannot reach ${domain}:443 from this VPS."
    fi

    if timeout 15 openssl s_client \
        -connect "${domain}:443" \
        -servername "${domain}" \
        -tls1_3 \
        -brief </dev/null 2>&1 |
        grep -Eq 'Protocol version: TLSv1\.3|Protocol.*TLSv1\.3'; then
        ok "TLS 1.3 handshake succeeded for ${domain}."
    else
        warn "TLS 1.3 verification was inconclusive for ${domain}."
        warn "The TCP test succeeded, but openssl did not return the expected TLS summary."
    fi

    SNI="${domain}"
}

select_sni() {
    local choice custom

    if [[ -n "${1:-}" ]]; then
        validate_sni "$1"
        return
    fi

    while true; do
        echo
        echo "============================================================"
        echo "Select REALITY SNI / Target"
        echo "============================================================"
        echo "1) www.microsoft.com"
        echo "2) www.apple.com"
        echo "3) www.google.com"
        echo "4) www.cloudflare.com"
        echo "5) Custom domain"
        echo "0) Exit"
        echo "============================================================"
        read -r -p "Enter your choice [1-5, 0]: " choice

        case "${choice}" in
            1) validate_sni "www.microsoft.com"; break ;;
            2) validate_sni "www.apple.com"; break ;;
            3) validate_sni "www.google.com"; break ;;
            4) validate_sni "www.cloudflare.com"; break ;;
            5)
                read -r -p "Enter custom SNI/domain: " custom
                validate_sni "${custom}"
                break
                ;;
            0) exit 0 ;;
            *) warn "Invalid choice." ;;
        esac
    done
}

install_xray() {
    if [[ -x "${XRAY_BIN}" ]]; then
        info "Xray is already installed."
    else
        info "Installing Xray from the official installer..."
        bash -c "$(curl -fsSL https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
    fi

    [[ -x "${XRAY_BIN}" ]] || die "Xray binary not found at ${XRAY_BIN}."

    local version
    version="$("${XRAY_BIN}" version 2>/dev/null | head -n 1 || true)"
    ok "Xray: ${version:-installed}"
}

detect_xray_service_account() {
    if ! id "${XRAY_SERVICE_USER}" >/dev/null 2>&1; then
        die "Xray service user '${XRAY_SERVICE_USER}' does not exist."
    fi

    XRAY_SERVICE_GROUP="$(id -gn "${XRAY_SERVICE_USER}")"
    [[ -n "${XRAY_SERVICE_GROUP}" ]] ||
        die "Unable to determine group for ${XRAY_SERVICE_USER}."

    ok "Xray service account: ${XRAY_SERVICE_USER}:${XRAY_SERVICE_GROUP}"
}

generate_credentials() {
    info "Generating Xray UUID..."
    UUID="$(uuidgen)"
    [[ -n "${UUID}" ]] || die "Failed to generate UUID."

    info "Generating X25519 key pair..."
    local key_output
    key_output="$("${XRAY_BIN}" x25519 2>&1)"

    PRIVATE_KEY="$(
        echo "${key_output}" |
        sed -n 's/^PrivateKey:[[:space:]]*//p' |
        head -n 1 | tr -d '\r'
    )"

    PUBLIC_KEY="$(
        echo "${key_output}" |
        sed -n 's/^Password (PublicKey):[[:space:]]*//p' |
        head -n 1 | tr -d '\r'
    )"

    if [[ -z "${PUBLIC_KEY}" ]]; then
        PUBLIC_KEY="$(
            echo "${key_output}" |
            sed -n 's/^PublicKey:[[:space:]]*//p' |
            head -n 1 | tr -d '\r'
        )"
    fi

    [[ -n "${PRIVATE_KEY}" ]] || die "Failed to extract X25519 private key."
    [[ -n "${PUBLIC_KEY}" ]] || die "Failed to extract X25519 public key."

    SHORT_ID="$(openssl rand -hex 8)"
    [[ -n "${SHORT_ID}" ]] || die "Failed to generate Short ID."

    ok "Credentials generated."
}

stop_xray_before_config() {
    if systemctl list-unit-files 2>/dev/null | grep -q '^xray\.service'; then
        info "Stopping Xray before replacing configuration..."
        systemctl stop xray || true
    fi
}

create_config() {
    info "Creating Xray v2 configuration..."

    mkdir -p "$(dirname "${XRAY_CONFIG}")"

    cat > "${XRAY_CONFIG}" <<EOF
{
  "log": {
    "loglevel": "warning"
  },
  "dns": {
    "servers": [
      "${DNS1}",
      "${DNS2}"
    ]
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": ${XRAY_PORT},
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "${UUID}",
            "flow": "${FLOW}"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "target": "${SNI}:443",
          "xver": 0,
          "serverNames": [
            "${SNI}"
          ],
          "privateKey": "${PRIVATE_KEY}",
          "shortIds": [
            "${SHORT_ID}"
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct",
      "sockopt": {
        "domainStrategy": "UseIPv4"
      }
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ]
}
EOF

    [[ -s "${XRAY_CONFIG}" ]] || die "Failed to create ${XRAY_CONFIG}"

    chown root:"${XRAY_SERVICE_GROUP}" "${XRAY_CONFIG}"
    chmod 640 "${XRAY_CONFIG}"

    chown root:root "$(dirname "${XRAY_CONFIG}")"
    chmod 755 "$(dirname "${XRAY_CONFIG}")"

    ok "Xray configuration created."
}

validate_json() {
    info "Validating JSON syntax..."
    jq empty "${XRAY_CONFIG}" >/dev/null 2>&1 ||
        die "JSON validation failed."
    ok "JSON syntax is valid."
}

validate_xray_config() {
    info "Testing Xray configuration..."

    local output
    if ! output="$("${XRAY_BIN}" run -test -config "${XRAY_CONFIG}" 2>&1)"; then
        echo "${output}"
        die "Xray configuration test failed."
    fi

    echo "${output}"
    ok "Xray configuration test passed."
}

configure_firewall() {
    if command -v ufw >/dev/null 2>&1 &&
       ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw allow 443/tcp >/dev/null
        ok "UFW allows TCP 443."
    fi

    if command -v iptables >/dev/null 2>&1; then
        if iptables -C INPUT -p tcp --dport 443 -j ACCEPT 2>/dev/null; then
            ok "iptables already allows TCP 443."
        else
            iptables -I INPUT -p tcp --dport 443 -j ACCEPT
            ok "iptables allows TCP 443."
        fi
    fi
}

start_xray() {
    systemctl daemon-reload
    systemctl enable xray >/dev/null 2>&1

    info "Starting Xray..."
    if ! systemctl restart xray; then
        systemctl status xray --no-pager -l || true
        journalctl -u xray -n 100 --no-pager || true
        die "Xray failed to start."
    fi

    sleep 2

    systemctl is-active --quiet xray ||
        die "Xray service is not active."

    ok "Xray service is running."
}

verify_port() {
    info "Checking TCP port ${XRAY_PORT}..."

    if ss -lntp 2>/dev/null |
        grep -Eq "(:|\])${XRAY_PORT}\b"; then
        ss -lntp 2>/dev/null | grep -E "(:|\])${XRAY_PORT}\b" || true
        ok "Xray is listening on TCP ${XRAY_PORT}."
    else
        systemctl status xray --no-pager -l || true
        journalctl -u xray -n 100 --no-pager || true
        die "TCP ${XRAY_PORT} is not listening."
    fi
}

post_install_network_test() {
    info "Running post-install network checks..."

    if dig +time=3 +tries=1 +short www.google.com A >/dev/null 2>&1; then
        ok "System DNS test passed."
    else
        warn "System DNS test failed; Xray is configured with DoH fallback."
    fi

    if curl -4 -fsSI --max-time 10 https://www.google.com >/dev/null 2>&1; then
        ok "Direct IPv4 HTTPS test passed."
    else
        warn "Direct IPv4 HTTPS test failed."
    fi

    if timeout 10 bash -c "cat < /dev/null > /dev/tcp/${SNI}/443" 2>/dev/null; then
        ok "REALITY target TCP 443 is reachable."
    else
        warn "REALITY target TCP 443 test failed after installation."
    fi
}

generate_vless_url() {
    # encryption=none is explicit for VLESS clients.
    VLESS_URL="vless://${UUID}@${SERVER_IP}:${XRAY_PORT}?encryption=none&type=tcp&security=reality&pbk=${PUBLIC_KEY}&fp=chrome&sni=${SNI}&sid=${SHORT_ID}&spx=%2F&flow=${FLOW}#Xray-REALITY-v2"
}

save_information() {
    cat > "${XRAY_INFO}" <<EOF
============================================================
XRAY VLESS + REALITY v2
============================================================

Server IP:
${SERVER_IP}

Port:
${XRAY_PORT}

Protocol:
VLESS

Transport:
TCP

Security:
REALITY

Flow:
${FLOW}

SNI / Server Name:
${SNI}

UUID:
${UUID}

Private Key:
${PRIVATE_KEY}

Public Key:
${PUBLIC_KEY}

Short ID:
${SHORT_ID}

Xray DNS:
${DNS1}
${DNS2}

VLESS URL:
${VLESS_URL}

============================================================
FILES
============================================================

Xray config:
${XRAY_CONFIG}

Connection information:
${XRAY_INFO}

============================================================
COMMANDS
============================================================

Check status:
systemctl status xray --no-pager

Restart:
systemctl restart xray

Stop:
systemctl stop xray

Start:
systemctl start xray

Logs:
journalctl -u xray -f

Recent logs:
journalctl -u xray -n 100 --no-pager

Config test:
xray run -test -config ${XRAY_CONFIG}

Port check:
ss -lntp | grep ':443'

DNS test:
dig www.google.com

Internet test:
curl -4 -I https://www.google.com --max-time 10

============================================================
EOF

    chown root:root "${XRAY_INFO}"
    chmod 600 "${XRAY_INFO}"
    ok "Connection information saved to ${XRAY_INFO}"
}

show_result() {
    echo
    echo "============================================================"
    echo "       Xray VLESS + REALITY v2 - Installation Complete"
    echo "============================================================"
    echo
    echo "Server IP : ${SERVER_IP}"
    echo "Port      : ${XRAY_PORT}"
    echo "Protocol  : VLESS"
    echo "Transport : TCP"
    echo "Security  : REALITY"
    echo "Flow      : ${FLOW}"
    echo "SNI       : ${SNI}"
    echo
    echo "UUID:"
    echo "${UUID}"
    echo
    echo "Public Key:"
    echo "${PUBLIC_KEY}"
    echo
    echo "Short ID:"
    echo "${SHORT_ID}"
    echo
    echo "VLESS URL:"
    echo "${VLESS_URL}"
    echo
    echo "Config:"
    echo "${XRAY_CONFIG}"
    echo
    echo "Info:"
    echo "${XRAY_INFO}"
    echo
    echo "IMPORTANT:"
    echo "  - Use Public Key on the client."
    echo "  - Never put the Private Key into v2rayN."
    echo "  - encryption=none is included in the VLESS URL."
    echo "  - Xray server DNS uses DoH: 1.1.1.1 + 8.8.8.8."
    echo
    systemctl status xray --no-pager -l | sed -n '1,15p' || true
    echo
}

main() {
    echo
    echo "============================================================"
    echo "       Xray VLESS + REALITY Installer v2"
    echo "============================================================"
    echo

    install_dependencies
    detect_public_ip
    check_server_internet
    check_local_port
    select_sni "${1:-}"
    install_xray
    detect_xray_service_account
    stop_xray_before_config
    generate_credentials
    create_config
    validate_json
    validate_xray_config
    configure_firewall
    start_xray
    verify_port
    post_install_network_test
    generate_vless_url
    save_information
    show_result

    ok "Installation completed successfully."
}

main "$@"
